### ISSUE TITLE
event creation form

### ISSUE THREAD

**Issue by eliblock** [Project-Mangrove/mgt656-spring-2015-project#15]
for EVENTS/NEW page
DONE: form for creating events that has attribute method="POST"
DONE: takes: title, location, image, year, month, day, hour, minute
See spec for details on input reqs.
DONE: Submit button: input element id="submit", type="submit"

**Comment by honeyzee** [comment]
the only thing left is taking in images

**Comment by eliblock** [comment]
Great! We realized it was just asking for a link to an image... so we added
that functionality, committed, and merged.
